defaults:
  - autoregressive_vla_config
  - _self_
  - vision_language_model@vlm_backbone: prismatic

_target_: versatil.models.decoding.decoders.factory.autoregressive_vla.AutoregressiveVLADecoder

input_keys: []
action_heads: {}

max_seq_len: 512
temperature: 1.0
learnable_temperature: false
deterministic: true
causal_prefix: true

observation_horizon: ${task.observation_horizon}
prediction_horizon: ${task.prediction_horizon}
action_space: ${task.action_space}
observation_space: ${task.observation_space}
device: ${experiment.device}
