# @package _global_
_target_: versatil.configs.main.MainConfig

defaults:
  - /task: base
  - /policy: base
  - /experiment: default
  - /task/dataset_schema: libero_lerobot
  - /task/dataloader: libero_lerobot
  - /task/action_space: libero_precomputed_lerobot
  - /task/observation_space: libero_rgb_proprio_lerobot
  - /training: ema
  - /policy/encoding_pipeline: smolvlm_embeddings
  - /policy/decoder: smolvla
  - /policy/algorithm: flow_matching
  - /policy/loss: regressionMSE_gripper
  - /inference: libero_lerobot
  - _self_

task:
  observation_horizon: 1
  prediction_horizon: 50
  dataloader:
    tokenization:
      tokenize_observations: true
      observation_tokenizer:
        tokenizer_model: HuggingFaceTB/SmolVLM2-500M-Instruct
        max_token_len: 48

experiment:
  precision: ${precision:BF16_MIXED}
  checkpoint_folder: ${checkpoint_dir:libero}
  checkpoint_every: 5

training:
  num_epochs: 200
  early_stopping_patience: 100
  clip_gradient_norm: true
  clip_max_norm: 10.0

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  validate_loss_keys: true
  loss:
    loss_modules:
      regression_loss:
        action_keys:
          - ${proprio_key:EE_POS_ACTION}
          - ${proprio_key:EE_ORI_ACTION}
      gripper_loss:
        key: ${proprio_key:GRIPPER_STATE_ACTION}
      trajectory_length:
        action_key: ${proprio_key:EE_POS_ACTION}
  decoder:
    input_keys:
      - vlm_fused_rgb_language
    proprioceptive_feature_key: robot_state_proprio
