# @package _global_
_target_: versatil.configs.main.MainConfig

defaults:
  - /task: base
  - /policy: base
  - /experiment: default
  - /task/dataset_schema: libero_lerobot
  - /task/dataloader: libero_lerobot
  - /task/action_space: libero_precomputed_lerobot
  - /task/observation_space: libero_rgb_proprio_lerobot
  - /training: default
  - /policy/encoding_pipeline: smolvlm_embeddings
  - /policy/decoder: smolvla_decoder
  - /policy/algorithm: flow_matching
  - /policy/loss: regression_gripper_mse
  - /inference: libero_lerobot
  - _self_

task:
  observation_horizon: 1
  prediction_horizon: 10
  observation_space:
    observations_metadata:
      ${proprio_key:GRIPPER_STATE}:
        needs_normalization: true
  dataloader:
    image_norm_type: ${image_norm_type:MINUS_ONE_TO_ONE}
    kinematics_norm_type: ${kinematics_norm_type:GAUSSIAN}
    tokenization:
      tokenize_observations: true
      observation_tokenizer:
        tokenizer_model: HuggingFaceTB/SmolVLM2-500M-Instruct
        max_token_len: 48
        padding_strategy: ${token_padding:MAX_LENGTH}

experiment:
  precision: ${precision:FP32}
  checkpoint_folder: ${checkpoint_dir:libero}
  checkpoint_every: 2

training:
  num_epochs: 8
  early_stopping_patience: 8
  clip_gradient_norm: true
  clip_max_norm: 10.0
  lr_schedule: "cosine"
  lr_warmup_steps: 1000
  optimizer:
    lr: 1.0e-4
    betas: [0.9, 0.95]
    weight_decay: 1.0e-10
    param_groups: []

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  validate_loss_keys: true
  loss:
    loss_modules:
      regression_loss:
        action_keys:
          - ${proprio_key:EE_POS_ACTION}
          - ${proprio_key:EE_ORI_ACTION}
        mse_weight: 1.0
        l1_weight: 0.0
      gripper_loss:
        action_keys:
          - ${proprio_key:GRIPPER_STATE_ACTION}
      trajectory_length:
        action_key: ${proprio_key:EE_POS_ACTION}
  decoder:
    input_keys:
      - vlm_fused_rgb_language
    proprioceptive_feature_key: robot_state_proprio
