defaults:
  - /policy/decoder/action_head@joint_action: base
  - _self_

joint_action:
  input_dim: ${mul:${action_space_prediction_dimension:${task.action_space}},4096}
  blocks:
    - _target_: versatil.models.decoding.action_heads.blocks.MLPBlock
      input_dim: ${...input_dim}
      hidden_dims:
        - 4096
      output_dim: null
      activation: ${activation_function:RELU}
      dropout: 0.0
      normalization: true
    - _target_: versatil.models.decoding.action_heads.blocks.ResidualBlock
      block:
        _target_: versatil.models.decoding.action_heads.blocks.MLPBlock
        input_dim: 4096
        hidden_dims:
          - 4096
        output_dim: null
        activation: ${activation_function:RELU}
        dropout: 0.0
        normalization: true
      dropout: 0.0
    - _target_: versatil.models.decoding.action_heads.blocks.ResidualBlock
      block:
        _target_: versatil.models.decoding.action_heads.blocks.MLPBlock
        input_dim: 4096
        hidden_dims:
          - 4096
        output_dim: null
        activation: ${activation_function:RELU}
        dropout: 0.0
        normalization: true
      dropout: 0.0
    - _target_: versatil.models.decoding.action_heads.blocks.LayerNormBlock
      input_dim: 4096
