${proprio_key:EE_POS_ACTION}:
  _target_: versatil.models.decoding.action_heads.ActionHead
  input_dimension: ${policy.decoder.embedding_dimension}
  blocks:
    - _target_: versatil.models.decoding.action_heads.blocks.MLPBlock
      input_dimension: ${policy.decoder.embedding_dimension}
      hidden_dimensions:
        - 256
        - 128
      output_dim: null
      activation: ${activation_function:RELU}
      dropout: ${policy.decoder.dropout_rate}
