# The syntax to validate against structured configs is always: `config_name in the configs.init.py`@`field path in the yaml file to validate`
defaults:
  - gaussian_mixture_nll@loss_modules.moe_loss.base_loss.loss_modules.action_nll
  - gripper_mixture_nll@loss_modules.moe_loss.base_loss.loss_modules.gripper_nll
  - traj_len@loss_modules.moe_loss.base_loss.loss_modules.trajectory_length
  - phase_classification@loss_modules.moe_loss.base_loss.loss_modules.phase_classification_loss
  - mmd@loss_modules.moe_loss.base_loss.loss_modules.maximum_mean_discrepancy
  - _self_

_target_: versatil.metrics.composite.CompositeLoss
loss_modules:
  moe_loss:
    _target_: versatil.metrics.components.MoELoss
    base_loss:
      _target_: versatil.metrics.composite.CompositeLoss
      loss_modules:
        action_nll:
          action_keys:
            - ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
          weight: 1.0
          learned_variance: false

        gripper_nll:
          key: ${proprio_key:GRIPPER_STATE}
          actions_metadata: ${task.action_space.actions_metadata}
          weight: 0.05

        maximum_mean_discrepancy:
            weight: 10.0

        trajectory_length:
            _target_: versatil.metrics.components.TrajectoryLengthLoss
            weight: 0.0
            action_key: ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}

        phase_classification_loss:
          key: ${obs_key:PHASE_LABEL}
          cross_entropy_weight: 0.1
          entropy_weight: 0.01
          label_smoothing: 0.0



