defaults:
  - regression@loss_modules.regression_loss
  - latent_optimal_transport@loss_modules.latent_ot
  - traj_len@loss_modules.trajectory_length
  - _self_

_target_: versatil.metrics.composite.CompositeLoss
loss_modules:
    regression_loss:
      _target_: versatil.metrics.components.RegressionLoss
      action_keys:
        - ${proprio_key:SYNTHETIC_POSITION_ACTION}
      mse_weight: 0.0
      l1_weight: 1.0
      huber_weight: 0.0

    latent_ot:
        weight: 0.01
        p: 2
        blur_fraction: 0.1
        reach_multiplier: 1.0

    trajectory_length:
        _target_: versatil.metrics.components.TrajectoryLengthLoss
        weight: 0.0
        action_key: ${proprio_key:SYNTHETIC_POSITION_ACTION}