defaults:
  - regression@loss_modules.regression_loss
  - gripper@loss_modules.gripper_loss
  - latent_optimal_transport@loss_modules.latent_wasserstein
  - _self_

_target_: versatil.metrics.CompositeLoss
loss_modules:
    regression_loss:
      _target_: versatil.metrics.RegressionLoss
      action_keys:
        - ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
      mse_weight: 0.0
      l1_weight: 1.0
      huber_weight: 0.0

    gripper_loss:
      _target_: versatil.metrics.GripperLoss
      key: ${proprio_key:GRIPPER_STATE}
      actions_metadata: ${task.action_space.actions_metadata}
      bce_weight: 0.05

    latent_wasserstein:
      weight: 20.0
      p: 2
      epsilon: 0.01

    trajectory_length:
        _target_: versatil.metrics.TrajectoryLengthLoss
        weight: 0.0
        action_key: ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}