defaults:
  - regression@loss_modules.regression_loss
  - conditional_mmd@loss_modules.conditional_mmd
  - traj_len@loss_modules.trajectory_length
  - _self_

_target_: versatil.metrics.composite.CompositeLoss
loss_modules:
    regression_loss:
      _target_: versatil.metrics.components.RegressionLoss
      action_keys:
        - ${proprio_key:SYNTHETIC_POSITION_ACTION}
      mse_weight: 0.0
      l1_weight: 1.0
      huber_weight: 0.0

    conditional_mmd:
        weight: 1.0
        state_weight: 1.0
        prior_target_key: ${latent_key:POSTERIOR_MU}
        condition_key: ${latent_key:PRIOR_CONDITION}
        kernel_type: ${kernel_type:IMQ}
        use_median_heuristic: false
        bandwidth_multipliers: [16, 32, 64, 128]
        condition_kernel_type: ${kernel_type:RBF}
        condition_use_median_heuristic: false
        condition_bandwidth_multipliers: [0.5, 1.0, 2.0]
        normalize_condition: true

    trajectory_length:
        _target_: versatil.metrics.components.TrajectoryLengthLoss
        weight: 0.0
        action_key: ${proprio_key:SYNTHETIC_POSITION_ACTION}
