defaults:
  - regression@loss_modules.regression_loss
  - vq_commitment@loss_modules.vq_commitment
  - vq_prior_ce@loss_modules.vq_prior_ce
  - traj_len@loss_modules.trajectory_length
  - _self_

_target_: versatil.metrics.composite.CompositeLoss
loss_modules:
    regression_loss:
      _target_: versatil.metrics.components.RegressionLoss
      action_keys:
        - ${proprio_key:SYNTHETIC_POSITION_ACTION}
      mse_weight: 0.0
      l1_weight: 1.0
      huber_weight: 0.0

    vq_commitment:
        _target_: versatil.metrics.components.VQCommitmentLoss
        weight: 1.0
        num_codes: ${policy.algorithm.posterior_encoder.num_codes}
        num_residual_layers: ${policy.algorithm.posterior_encoder.num_residual_layers}

    vq_prior_ce:
        _target_: versatil.metrics.components.VQPriorCrossEntropyLoss
        weight: 1.0

    trajectory_length:
        _target_: versatil.metrics.components.TrajectoryLengthLoss
        weight: 0.0
        action_key: ${proprio_key:SYNTHETIC_POSITION_ACTION}
