defaults:
  - token_loss@loss_modules.token_loss
  - kl@loss_modules.kl_divergence
  - denoising_prior@loss_modules.denoising_prior
  - _self_

_target_: versatil.metrics.composite.CompositeLoss

loss_modules:
  token_loss:
    label_smoothing: 0.0
  kl_divergence:
    weight: 10.0
  denoising_prior:
    weight: 0.05

weights:
  token_loss: 1.0
  kl_divergence: 1.0
  denoising_prior: 1.0