defaults:
  - csv
  - zarr_meta/bowel_retraction@metadata
  - _self_

_target_: versatil.data.raw.schemas.custom.bowel_retraction.BowelRetractionSchema
zarr_path: ${zarr_dir:bowel_retraction/in_vivo/dataset.zarr}
dataset_folders:
  - ${bowel_retraction_dir:in_vivo}
  - ${bowel_retraction_dir:invivo_041225}
