defaults:
  - encoder/image/cnn@encoders.left
  - encoder/language@encoders.instruction
  - _self_

_target_: versatil.models.encoding.pipeline.EncodingPipeline
observation_space: ${task.observation_space}

encoders:
  left:
    _target_: versatil.models.encoding.encoders.rgb.cnn.CNNEncoder
    input_keys:
    - ${cameras:LEFT}
    backbone: ${rgb_backbone:EFFICIENTNET_B0}
    pretrained: true
    frozen: false
    pooling_method: none
    batch_norm_handling: ${batch_norm_handling:FROZEN}


  instruction:
    model_name: ${language_model:GEMMA_2B}
    pretrained: true
    frozen: true
    max_token_len: ${task.dataloader.tokenization.observation_tokenizer.max_token_len}
    use_embeddings_only: true

fusion_stages: []
