defaults:
  - encoder/proprio@encoders.robot_state
  - _self_

_target_: versatil.models.encoding.pipeline.EncodingPipeline
observation_space: ${task.observation_space}

encoders:
  vlm:
    _target_: versatil.models.encoding.encoders.cross_modal.vision_language.paligemma.PaliGemmaEncoder
    input_keys:
      - ${cameras:AGENTVIEW}
      - ${cameras:EYE_IN_HAND}
      - ${sample_key:TOKENIZED_OBSERVATIONS}
    model_name: google/paligemma-3b-pt-224
    pretrained: true
    frozen: true
    use_embeddings_only: true
    max_text_length: ${task.dataloader.tokenization.observation_tokenizer.max_token_len}

  robot_state:
    input_keys:
      - ${proprio_key:EE_POS}
      - ${proprio_key:EE_ORI}
      - ${proprio_key:GRIPPER_STATE}
    output_dim: 1024
    pretrained: false
    frozen: false

fusion_stages: []
