defaults:
  - encoder/image/cnn@encoders.left
  - encoder/image/cnn@encoders.right
  - _self_

_target_: versatil.models.encoding.pipeline.EncodingPipeline
observation_space: ${task.observation_space}

encoders:
  left:
    _target_: versatil.models.encoding.encoders.rgb.cnn.CNNEncoder
    input_keys:
    - ${cameras:LEFT}
    backbone: ${rgb_backbone:EFFICIENTNET_B0}
    pretrained: true
    frozen: false
    pooling_method: ${pooling_method:SPATIAL_SOFTMAX}
    batch_norm_handling: ${batch_norm_handling:FROZEN}

  right:
    _target_: versatil.models.encoding.encoders.rgb.cnn.CNNEncoder
    input_keys:
    - ${cameras:RIGHT}
    backbone: ${rgb_backbone:EFFICIENTNET_B0}
    pretrained: true
    frozen: false
    pooling_method: ${pooling_method:SPATIAL_SOFTMAX}
    batch_norm_handling: ${batch_norm_handling:FROZEN}

