defaults:
  - /policy/adaptation/lora@lora_config: vlm_text_model_attention_and_feedforward
  - _self_

_target_: versatil.models.decoding.generative_language_models.vision_language.smolvlm.SmolVLM

input_keys:
  - ${cameras:AGENTVIEW}
  - ${cameras:EYE_IN_HAND}
model_name: ${smolvlm_model:SMOLVLM_500M}
pretrained: true
frozen: false
max_text_length: ${task.dataloader.tokenization.observation_tokenizer.max_token_len}
model_dtype: ${experiment.precision}
