_target_: albumentations.Compose
transforms:
  - _target_: albumentations.GaussianBlur
    blur_limit: [3, 7]
    p: 0.5
  - _target_: albumentations.CoarseDropout
    max_holes: 8
    max_height: 8
    max_width: 8
    p: 0.3
  - _target_: albumentations.ShiftScaleRotate
    rotate_limit: [0, 0]
    scale_limit: [-0.5, 0.6]
    shift_limit: [-0.0625, 0.0625]
    p: 0.5