# @package _global_
_target_: versatil.configs.main.MainConfig

defaults:
  - /task: base
  - /policy: base
  - /experiment: default
  - /task/dataset_schema: endoscope_guidance_phantom_5hz
  - /task/dataloader: endoscope_guidance
  - /task/action_space: camera_frame_position_and_roll
  - /task/observation_space: stereo_rgb_language
  - /training: default
  - /policy/encoding_pipeline: stereo_rgb_language_encoder
  - /policy/decoder: action_transformer_language
  - /policy/algorithm: behavioral_cloning
  - /policy/loss: regression_camera_frame_position_and_roll
  - override /policy/decoder/heads@policy.decoder.action_heads: camera_frame_position_and_roll
  - _self_

task:
  observation_horizon: 1
  prediction_horizon: 10
  dataloader:
    tokenization:
      observation_tokenizer:
        tokenizer_model: ${language_model:MINI_LM_L6}

experiment:
  precision: ${precision:FP32}
  checkpoint_folder: ${checkpoint_dir:endoscope_guidance_phantom_5hz}
  checkpoint_every: 5

training:
  num_epochs: 100
  early_stopping_patience: 200
  lr_schedule: null
  clip_gradient_norm: true
  clip_max_norm: 1.0

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  decoder:
    embedding_dimension: 256
    feedforward_dimension: 1024
    number_of_layers: 4
  loss:
    loss_modules:
      regression_loss:
        action_keys:
          - ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
          - ${proprio_key:RELATIVE_PIVOT_ROLL}
      trajectory_length:
        action_key: ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
  encoding_pipeline:
    encoders:
      instruction:
        model_name: ${language_model:MINI_LM_L6}
