defaults:
  - base

_target_: versatil.data.task.ActionSpace
use_gripper_class_weights: false
denoise_actions: false

actions_metadata:
  ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}:
    _target_: versatil.data.metadata.OnTheFlyActionMetadata
    source_metadata:
      _target_: versatil.data.metadata.PositionObservationMetadata
      raw_data_column_keys: [camera_frame_tip_position_x, camera_frame_tip_position_y, camera_frame_tip_position_z]
      dtype: float32
      dimension: 3
      needs_normalization: true
      frame: ${coordinate_system:CAMERA}
    computation_method: ${action_computation:DELTA}

  ${proprio_key:RELATIVE_PIVOT_ROLL}:
    _target_: versatil.data.metadata.OnTheFlyActionMetadata
    source_metadata:
      _target_: versatil.data.metadata.OrientationObservationMetadata
      raw_data_column_keys: [relative_pivot_roll]
      dtype: float32
      dimension: 1
      needs_normalization: true
      frame: ${coordinate_system:UNKNOWN}
      orientation_representation: ${orientation:ROLL}
    computation_method: ${action_computation:DELTA}
