defaults:
  - /quantization/workflow@_here_: eager
  - _self_

quantize_config:
  _target_: torchao.quantization.Int8DynamicActivationIntxWeightConfig
  weight_dtype: ${torch_dtype:int4}
  weight_granularity:
    _target_: torchao.quantization.PerGroup
    group_size: 32
is_qat: true
module_paths: []
auto_filter_incompatible_linears: true
