defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${proprio_key:ROBOT_FRAME_CARTESIAN_TIP_POS}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [relative_tip_position_x, relative_tip_position_y, relative_tip_position_z]
    dtype: float32
    dimension: 3
    needs_normalization: true
    frame: ${coordinate_system:ROBOT_BASE}

  ${proprio_key:GRIPPER_STATE}:
    _target_: versatil.data.metadata.GripperObservationMetadata
    raw_data_column_keys: [open]
    dtype: int8
    dimension: 1
    needs_normalization: false
    gripper_type: ${gripper:BINARY}
    binary_gripper_range: ${gripper_range:ZERO_ONE}

  ${cameras:LEFT}:
    _target_: versatil.data.metadata.RGBCameraMetadata
    camera_key: ${cameras:LEFT}
    dtype: uint8
    image_width: 270
    image_height: 270

  ${cameras:RIGHT}:
    _target_: versatil.data.metadata.RGBCameraMetadata
    camera_key: ${cameras:RIGHT}
    dtype: uint8
    image_width: 270
    image_height: 270

precomputed_actions: {}
