# @package _global_

defaults:
  - /experiment: default
  - /task/dataset_schema: bowel_retraction_v2
  - /task/dataloader: bowel_retraction_tokenized_actions
  - /task/action_space: deltas_cf_pos_gripper
  - /task/observation_space: stereo_rgb
  - /training: gpt_decoder_default
  - /policy/encoding_pipeline: stereo_rgb
  - /policy/decoder: discrete_detr_transformer
  - /policy/algorithm: behavioral_cloning
  - /policy/loss: tokenCE
  - /inference: default
  - override /task/dataloader/tokenization: action_fast
  - _self_

experiment:
  checkpoint_folder: ${checkpoint_dir:bowel_retraction}

task:
  observation_horizon: 1
  prediction_horizon: 10

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  validate_loss_keys: true
