defaults:
  - base

_target_: versatil.data.task.ActionSpace
use_gripper_class_weights: false
denoise_actions: false

actions_metadata:
  ${proprio_key:UR3_EE_TARGET_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:UNKNOWN}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 2
    prediction_dimension: 2
    needs_normalization: true
