# @package _global_
_target_: versatil.configs.main.MainConfig

defaults:
  - /task: base
  - /policy: base
  - /experiment: default
  - /task/dataset_schema: metaworld_mt50
  - /task/dataloader: metaworld
  - /task/action_space: metaworld_mt50_precomputed
  - /task/observation_space: metaworld_mt50_rgb
  - /training: default
  - /policy/encoding_pipeline: mono_rgb_language_encoder
  - /policy/decoder: action_transformer_language
  - /policy/algorithm: behavioral_cloning
  - /policy/loss: regression_continuous_gripper
  - /inference: default
  - override /policy/decoder/heads@policy.decoder.action_heads: metaworld_mt50
  - _self_

task:
  observation_horizon: 1
  prediction_horizon: 10
  dataloader:
    tokenization:
      observation_tokenizer:
        tokenizer_model: ${language_model:BERT_BASE}

experiment:
  precision: ${precision:FP32}
  checkpoint_folder: ${checkpoint_dir:metaworld}

training:
  num_epochs: 200
  early_stopping_patience: 100
  lr_schedule: null
  clip_gradient_norm: true
  clip_max_norm: 1.0

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  validate_loss_keys: true
  decoder:
    input_keys:
      - left_rgb
      - instruction_language
    embedding_dimension: 128
    feedforward_dimension: 512
    number_of_layers: 3
    activation: ${activation_function:SILU}
    attention_type: ${attention:MULTI_HEAD}
    number_of_key_value_heads: null
  encoding_pipeline:
    encoders:
        left:
            input_keys:
              - ${cameras:AGENTVIEW}
        instruction:
          model_name: ${language_model:BERT_BASE}

# Override specific parameters from defaults/command line if needed
# For example, to use different batch size:
# task.dataloader.batch_size: 64
# To override specific config components from command line, you can do for example
# ```policy/loss=mmd_l1_pos_gripper_bce``` to use MMD instead of KL in your loss
