defaults:
  - csv
  - zarr_meta/bowel_retraction@metadata
  - _self_

_target_: versatil.data.raw.schemas.custom.tso.TSODatasetSchema
dataset_type: ${dataset_type:TSO}
zarr_path: ${zarr_dir:bowel_retraction/in_vivo/dataset.zarr}
dataset_folders:
  - ${dataset_dir:VERSATIL_BOWEL_RETRACTION_DIR,in_vivo}
  - ${dataset_dir:VERSATIL_BOWEL_RETRACTION_DIR,invivo_041225}
