defaults:
  - lerobot
  - zarr_meta/kitchen@metadata

_target_: versatil.data.raw.schemas.lerobot.LeRobotDatasetSchemaV30
dataset_type: ${dataset_type:KITCHEN}
dataset_path: ${dataset_dir:VERSATIL_KITCHEN_LEROBOT_DIR}
zarr_path: ${zarr_dir:kitchen.zarr}
