defaults:
  - zarr_meta/multimodal_peg_transfer@metadata
  - _self_

_target_: versatil.data.raw.schemas.custom.tso.TSODatasetSchema
dataset_type: ${dataset_type:TSO}
zarr_path: ${zarr_dir:multimodal_peg_transfer/dataset.zarr}
dataset_folders:
  - ${dataset_dir:VERSATIL_MULTIMODAL_PEG_TRANSFER_DIR}
use_rectified_images: false
rgb_image_crops:
  ${cameras:LEFT}:
    x_min: 160
    y_min: 0
    x_max: 700
    y_max: 540
  ${cameras:RIGHT}:
    x_min: 260
    y_min: 0
    x_max: 800
    y_max: 540
