defaults:
  - lerobot
  - zarr_meta/pusht@metadata

_target_: versatil.data.raw.schemas.lerobot.LeRobotDatasetSchemaV30
dataset_type: ${dataset_type:PUSHT}
dataset_path: ${dataset_dir:VERSATIL_PUSHT_LEROBOT_DIR}
zarr_path: ${zarr_dir:pusht.zarr}
