defaults:
  - phase_act
  - heads@action_heads: bowel_retraction_phase

_target_: versatil.models.decoding.decoders.factory.phase_act.PhaseACT

# Key is always "{encoder_name}_{EncoderOutputType.value}" for each encoder in the encoding pipeline
input_keys:
  - left_rgb
  - right_rgb
  - instruction_language

embedding_dimension: 512
number_of_heads: 8
feedforward_dimension: 3200
number_of_encoder_layers: 4
number_of_decoder_layers: 4

activation: ${activation_function:RELU}
dropout_rate: 0.1
normalize_before: false

phase_routing_key: phase_label

observation_horizon: ${task.observation_horizon}
prediction_horizon: ${task.prediction_horizon}
action_space: ${task.action_space}
observation_space: ${task.observation_space}
device: ${experiment.device}