_target_: versatil.metrics.regularizers.FiniteDifferenceLipschitzRegularizer
input_domain: encoded_features
input_keys:
  - left_rgb
  - right_rgb
output_keys: null
weight: 1.0
target: 0.01
noise_scale: 0.01
detach_inputs: true
max_batch_size: 8
apply_during_eval: false
eps: 1.0e-12
disable_decoder_stochastic: true
scale_by_dimension_ratio: false
perturbation_mode: gaussian_channel_broadcast
