_target_: versatil.metrics.regularizers.FiniteDifferenceLipschitzRegularizer
input_domain: encoded_features
input_keys:
  - left_rgb
  - right_rgb
output_keys: null
weight: 0.001
target: 1.0
noise_scale: 0.01
symmetric: true
detach_inputs: true
max_batch_size: 8
apply_during_eval: false
eps: 1.0e-12
disable_decoder_stochastic: true
