defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${proprio_key:KITCHEN_ARM_QPOS}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 9
    is_numerical: true
    needs_normalization: true
    slice_start: 0
    slice_end: 9

  ${proprio_key:KITCHEN_OBJECT_QPOS}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 21
    is_numerical: true
    needs_normalization: true
    slice_start: 9
    slice_end: 30

  ${proprio_key:KITCHEN_TASK_GOAL}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [observation.task_goal]
    dtype: float32
    dimension: 7
    is_numerical: true
    needs_normalization: false

  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${raw_camera:IMAGE_KITCHEN}
    dtype: uint8
    channels: 3
    image_width: 112
    image_height: 112

precomputed_actions:
  ${proprio_key:KITCHEN_ARM_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:UNKNOWN}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 9
    prediction_dimension: 9
    needs_normalization: true
