defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${proprio_key:EE_POS}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 3
    needs_normalization: true
    slice_start: 0
    slice_end: 3
    frame: ${coordinate_system:ROBOT_BASE}

  ${proprio_key:EE_ORI}:
    _target_: versatil.data.metadata.OrientationObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 3
    needs_normalization: true
    slice_start: 3
    slice_end: 6
    frame: ${coordinate_system:ROBOT_BASE}
    orientation_representation: ${orientation:EULER}

  ${proprio_key:GRIPPER_STATE}:
    _target_: versatil.data.metadata.GripperObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 2
    needs_normalization: false
    slice_start: 6
    slice_end: 8
    gripper_type: ${gripper:CONTINUOUS}

  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:IMAGE}
    dtype: uint8
    channels: 3
    image_width: 256
    image_height: 256

  ${cameras:EYE_IN_HAND}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:IMAGE_2}
    dtype: uint8
    channels: 3
    image_width: 256
    image_height: 256

  ${obs_key:LANGUAGE}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [task]
    dtype: str
    dimension: 1
    is_numerical: false
    needs_normalization: false

precomputed_actions:
  ${proprio_key:EE_POS_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:ROBOT_BASE}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 7
    prediction_dimension: 3
    needs_normalization: true
    slice_start: 0
    slice_end: 3

  ${proprio_key:EE_ORI_ACTION}:
    _target_: versatil.data.metadata.OrientationActionMetadata
    frame: ${coordinate_system:ROBOT_BASE}
    orientation_representation: ${orientation:EULER}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 7
    prediction_dimension: 3
    needs_normalization: true
    slice_start: 3
    slice_end: 6

  ${proprio_key:GRIPPER_STATE_ACTION}:
    _target_: versatil.data.metadata.GripperActionMetadata
    gripper_type: ${gripper:BINARY}
    binary_gripper_range: ${gripper_range:MINUS_ONE_ONE}
    raw_data_column_keys: [action]
    dtype: int8
    storage_dimension: 7
    prediction_dimension: 1
    needs_normalization: false
    slice_start: 6
    slice_end: 7