defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${proprio_key:EE_POS}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 3
    needs_normalization: true
    slice_start: 0
    slice_end: 3
    frame: ${coordinate_system:ROBOT_BASE}

  ${proprio_key:GRIPPER_STATE}:
    _target_: versatil.data.metadata.GripperObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 1
    needs_normalization: false
    slice_start: 3
    slice_end: 4
    gripper_type: ${gripper:CONTINUOUS}

  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:IMAGE_METAWORLD_LEROBOT}
    dtype: uint8
    channels: 3
    image_width: 480
    image_height: 480

  ${obs_key:LANGUAGE}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [task]
    dtype: str
    dimension: 1
    is_numerical: false
    needs_normalization: false

precomputed_actions:
  ${proprio_key:EE_POS_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:ROBOT_BASE}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 4
    prediction_dimension: 3
    needs_normalization: true
    slice_start: 0
    slice_end: 3

  ${proprio_key:GRIPPER_STATE_ACTION}:
    _target_: versatil.data.metadata.GripperActionMetadata
    gripper_type: ${gripper:CONTINUOUS}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 4
    prediction_dimension: 1
    needs_normalization: false
    slice_start: 3
    slice_end: 4