defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${proprio_key:EE_POS}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 2
    needs_normalization: true
    slice_start: 0
    slice_end: 2
    frame: ${coordinate_system:UNKNOWN}

  ${proprio_key:PUSHT_BLOCK_POS}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 2
    needs_normalization: true
    slice_start: 2
    slice_end: 4
    frame: ${coordinate_system:UNKNOWN}

  ${proprio_key:PUSHT_BLOCK_ANGLE}:
    _target_: versatil.data.metadata.OrientationObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 1
    needs_normalization: true
    slice_start: 4
    slice_end: 5
    frame: ${coordinate_system:UNKNOWN}
    orientation_representation: ${orientation:ROLL}

  ${proprio_key:PUSHT_KEYPOINTS}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 18
    is_numerical: true
    needs_normalization: true
    slice_start: 5
    slice_end: 23

  ${proprio_key:PUSHT_CONTACTS}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [observation.state]
    dtype: float32
    dimension: 1
    is_numerical: true
    needs_normalization: false
    slice_start: 23
    slice_end: 24

  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${raw_camera:IMAGE_PUSHT}
    dtype: uint8
    channels: 3
    image_width: 96
    image_height: 96

precomputed_actions:
  ${proprio_key:EE_POS_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:UNKNOWN}
    raw_data_column_keys: [action]
    dtype: float32
    storage_dimension: 2
    prediction_dimension: 2
    needs_normalization: true
