defaults:
  - base

_target_: versatil.data.raw.zarr_meta.DatasetMetadata

observations:
  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:AGENTVIEW}
    dtype: uint8
    channels: 3
    image_width: 64
    image_height: 64

  ${proprio_key:SYNTHETIC_POSITION}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [x, y]
    dtype: float32
    dimension: 2
    needs_normalization: true
    frame: ${coordinate_system:UNKNOWN}

  ${synthetic_obs_key:CONTEXT}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [c0, c1, c2]
    dtype: float32
    dimension: 3
    is_numerical: true
    needs_normalization: false

  ${synthetic_obs_key:MODE_ID}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [mode]
    dtype: uint8
    dimension: 1
    is_numerical: true
    needs_normalization: false

precomputed_actions:
  ${proprio_key:SYNTHETIC_POSITION_ACTION}:
    _target_: versatil.data.metadata.PositionActionMetadata
    frame: ${coordinate_system:UNKNOWN}
    raw_data_column_keys: [dx, dy]
    dtype: float32
    storage_dimension: 2
    prediction_dimension: 2
    needs_normalization: true