defaults:
  - base

_target_: versatil.data.task.ObservationSpace

observations_metadata:
  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${raw_camera:IMAGE_METAWORLD}
    dtype: uint8
    channels: 3
    image_width: 480
    image_height: 480

  ${obs_key:LANGUAGE}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [task]
    dtype: str
    dimension: 1
    is_numerical: false
    needs_normalization: false