defaults:
  - base

_target_: versatil.data.task.ObservationSpace

observations_metadata:
  ${cameras:SYNTHETIC_TOP}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:SYNTHETIC_TOP}
    dtype: uint8
    channels: 3
    image_width: 64
    image_height: 64

  ${proprio_key:SYNTHETIC_POSITION}:
    _target_: versatil.data.metadata.PositionObservationMetadata
    raw_data_column_keys: [x, y]
    dtype: float32
    dimension: 2
    needs_normalization: true
    frame: ${coordinate_system:UNKNOWN}

  ${obs_key:SYNTHETIC_CONTEXT}:
    _target_: versatil.data.metadata.ObservationMetadata
    raw_data_column_keys: [c0, c1, c2]
    dtype: float32
    dimension: 3
    is_numerical: true
    needs_normalization: false