defaults:
  - base

_target_: versatil.data.task.ObservationSpace

observations_metadata:
  ${cameras:AGENTVIEW}:
    _target_: versatil.data.metadata.CameraMetadata
    camera_key: ${cameras:AGENTVIEW}
    dtype: uint8
    channels: 3
    image_width: 64
    image_height: 64