${proprio_key:SYNTHETIC_POSITION_ACTION}:
  _target_: versatil.models.decoding.action_heads.ActionHead
  input_dim: ${policy.decoder.embedding_dimension}
  blocks:
    - _target_: versatil.models.decoding.action_heads.blocks.MLPBlock
      input_dim: ${policy.decoder.embedding_dimension}
      hidden_dims:
        - 32
      output_dim: null
      activation: ${activation_function:RELU}
      dropout: ${policy.decoder.dropout_rate}