defaults:
  - optimal_transport@loss_modules.ot_loss
  - gripper@loss_modules.gripper_loss
  - mmd@loss_modules.maximum_mean_discrepancy
  - _self_

_target_: versatil.metrics.losses.composite.CompositeLoss
loss_modules:
    ot_loss:
      _target_: versatil.metrics.losses.optimal_transport.OptimalTransportLoss
      action_keys:
        - ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
      weight: 1.0
      p: 2
      blur_fraction: 0.1
      reach_multiplier: null
      expected_std: 0.577
      time_scale: 1.0

    gripper_loss:
      _target_: versatil.metrics.losses.gripper.GripperLoss
      key: ${proprio_key:GRIPPER_STATE}
      actions_metadata: ${task.action_space.actions_metadata}
      bce_weight: 0.05

    maximum_mean_discrepancy:
            weight: 100.0

    trajectory_length:
        _target_: versatil.metrics.losses.trajectory.TrajectoryLengthLoss
        weight: 0.1
        action_key: ${proprio_key:CAMERA_FRAME_CARTESIAN_TIP_POS}
