defaults:
  - /quantization/workflow/pt2e
  - _self_

targets:
  - _target_: versatil.quantization.module_target.PT2EQuantizationModuleTarget
    module_path: ""
    pt2e_backend:
      _target_: versatil.quantization.pt2e.backends.xnnpack.XNNPACKPT2EBackend
      is_dynamic: false
      is_qat: false
      is_per_channel: true
