# @package _global_
_target_: versatil.configs.main.MainConfig

defaults:
  - /task: base
  - /policy: base
  - /experiment: default
  - /task/dataset_schema: synthetic/circle
  - /task/dataloader: synthetic_default
  - /task/action_space: synthetic_2d
  - /task/observation_space: synthetic_image_state
  - /training: default
  - /policy/encoding_pipeline: mono_rgb
  - /policy/decoder: action_transformer
  - /policy/algorithm: bc_with_learned_prior
  - /policy/loss: regression_MMD
  - /inference: default
  - override /policy/decoder/heads@policy.decoder.action_heads: synthetic_2d
  - _self_

task:
  observation_horizon: 1
  prediction_horizon: 60

experiment:
  checkpoint_folder: ${checkpoint_dir:synthetic}

policy:
  _target_: versatil.models.policy.Policy
  observation_space: ${task.observation_space}
  action_space: ${task.action_space}
  prediction_horizon: ${task.prediction_horizon}
  observation_horizon: ${task.observation_horizon}
  device: ${experiment.device}
  validate_loss_keys: true
  encoding_pipeline:
    encoders:
      left:
        input_keys:
          - ${cameras:AGENTVIEW}
        backbone: ${rgb_backbone:MOBILENETV4_SMALL_050}
  decoder:
    input_keys:
      - left_rgb
    embedding_dimension: 64
    number_of_heads: 4
    feedforward_dimension: 128
    number_of_layers: 2

  algorithm:
    sampling_from_prior_probability: 0.0
    posterior_encoder:
        latent_dimension: 2
        embedding_dimension: 64
        number_of_heads: 4
        feedforward_dimension: 128
        number_of_encoder_layers: 1
        dropout_rate: 0.1
        device: ${policy.device}
        min_logvar: -4.0
    prior:
        latent_dimension: 2
        embedding_dimension: 64
        number_of_heads: 4
        feedforward_dimension: 128
        number_of_encoder_layers: 1
        dropout_rate: 0.1
        device: ${policy.device}
        min_logvar: -4.0
